export const packagesData = [
  {
    id: 1,
    title: "Romantic Maldives Escape",
    category: "Honeymoon",
    price: 125000,
    days: 5,
    resort: "Sun Siyam Olhuveli",
    images: [
      "/maldives2.jpg",
      "/m1.jpg",
      "/m3.jpg",
      "/m4.jpg",
      "/m5.jpg",
       ],
  },
  {
    id: 2,
    title: "Luxury Water Villa Experience",
    category: "Luxury",
    price: 250000,
    days: 6,
    resort: "Soneva Jani",
    images: [
      "/lu.jpg",
      "/lu1.jpg",
      "/lu2.jpg",
      "/lu3.jpg",
      "/lu4.jpg",
    ],
  },
  {
    id: 3,
    title: "Budget Maldives Getaway",
    category: "Budget",
    price: 75000,
    days: 4,
    resort: "Arena Beach Hotel",
    images: [
      "/n1.jpg",
      "/n2.jpg",
      "/n3.jpg",
      "/n4.jpg",
      "/n5.jpg",
    ],
  },
  {
    id: 4,
    title: "Luxury Honeymoon Retreat",
    category: "Honeymoon",
    price: 280000,
    days: 7,
    resort: "Baros Maldives",
    images: [
      "/p1.jpg",
      "/p2.jpg",
      "/p3.jpg",
      "/p4.jpg",
      "/p5.jpg",
    ],
  },
  {
    id: 5,
    title: "Romantic Maldives",
    category: "Honeymoon",
    price: 125000,
    days: 5,
    resort: "Sun Siyam Olhuveli",
    images: [
      "/maldives2.jpg",
      "/m1.jpg",
      "/m3.jpg",
      "/m4.jpg",
      "/m5.jpg",
    ],
  },
  {
    id: 6,
    title: "Luxury Water Villa",
    category: "Luxury",
    price: 250000,
    days: 6,
    resort: "Soneva Jani",
    images: [
      "/lu.jpg",
      "/lu1.jpg",
      "/lu2.jpg",
      "/lu3.jpg",
      "/lu4.jpg",
    ],
  },
  {
    id: 7,
    title: "Budget Maldives",
    category: "Budget",
    price: 75000,
    days: 4,
    resort: "Arena Beach Hotel",
    images: [
      "/n1.jpg",
      "/n2.jpg",
      "/n3.jpg",
      "/n4.jpg",
      "/n5.jpg",
    ],
  },
  {
    id: 8,
    title: "Honeymoon Retreat",
    category: "Honeymoon",
    price: 280000,
    days: 7,
    resort: "Baros Maldives",
    images: [
      "/p1.jpg",
      "/p2.jpg",
      "/p3.jpg",
      "/p4.jpg",
      "/p5.jpg",
    ],
  },
];
